import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
    docsSidebar: [
        'quick-start',
    ],
    apiSidebar: [
        { type: 'autogenerated', dirName: 'api' },
    ],
};

export default sidebars;
