name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test-coverage


#  test-docs-deployment:
#    runs-on: ubuntu-latest
#
#    defaults:
#      run:
#        working-directory: ./docs
#
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#
#      - uses: pnpm/action-setup@v4
#        with:
#          run_install: false
#
#      - uses: actions/setup-node@v4
#        with:
#          node-version: 22
#          cache: pnpm
#
#      - name: Install dependencies
#        run: pnpm install
#
#      - name: Test build website
#        run: pnpm run build
