name: Publish package to NPM

on:
  workflow_dispatch:


jobs:

  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22 ]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run test
      - run: pnpm run build
      - run: pnpm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
