name: Publish package to NPM

on:
  workflow_dispatch:


jobs:

  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: 'pnpm'

      - name: Wait for OTP input
        uses: step-security/wait-for-secrets@v1
        id: wait-for-secrets
        with:
          secrets: |
            OTP: 
              name: 'OTP to publish package'
              description: 'OTP from authenticator app'

      - run: pnpm install
      - run: pnpm run test
      - run: pnpm run build

      - name: Publish package
        run: pnpm publish --otp ${{ steps.get-otp.outputs.OTP }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
